### ISSUE TITLE
Bring dependabot auto-update back without breaking the deploy every week

### ISSUE THREAD

**Issue by sourishkrout** [stateful/docs.runme.dev#128]
Dependabot PRs were merged irrespective whether or not a Vercel deploy succeeded.

https://github.com/stateful/runme.dev/pull/127/commits/73eb72e7cb253a38a07775bcf945122d23b40b7a

**Comment by christian-bromann** [comment]
Just fyi: it doesn't seem like the fix worked so I will re-open and continue to investigate.

**Comment by sourishkrout** [comment]
K. Feel free to be a bit more forceful just promise me to not leave broken unattended.

**Comment by christian-bromann** [comment]
It seems to work now. Closing.
