### ISSUE TITLE
UriHandler / Launcher

### ISSUE THREAD

**Issue by sourishkrout** [stateful/docs.runme.dev#173]
Let's have the relevant parts of the blog below in the docs. Probably need to figure out a good name for this.

https://runme.dev/blog/runme-blog-launcher

**Comment by christian-bromann** [comment]
@sourishkrout what about this section: https://docs.runme.dev/features#run-with-runme-deep-linking ?

**Comment by sourishkrout** [comment]
Oh! Must have overlooked it. Sorry. Let's be sure it's up to date and close the ticket.

**Comment by christian-bromann** [comment]
Yes, the docs are still up to date. Closing.
