### ISSUE TITLE
Typo on configuration document

### ISSUE THREAD

**Issue by joseeantonior** [stateful/docs.runme.dev#241]
Reported by brucecastrow on DIscord:

Small typo on https://docs.runme.dev/configuration#cell-level-options 

> For example, code blocks can be to be:

**Comment by sourishkrout** [comment]
@edeediong can you please take a look when you have a chance. thanks!

**Comment by joseeantonior** [comment]
@edeediong I'll go ahead and address this directly.

**Comment by joseeantonior** [comment]
Addressed on commit e2d78ce
