### ISSUE TITLE
One-Click Installation with Welcome Repo

### ISSUE THREAD

**Issue by mxsdev** [stateful/docs.runme.dev#93]
For the "Install Extension" page, we currently tell users to install manually by finding the extension in the marketplace.

Since the one-click repo viewer we built earlier will prompt the user to install the extension, we could promote a "one-click install" method by using a link to a repo. 

I think it would be nice to link to a "welcome repo" that just demonstrates runme's capabilities and links to the getting started guide. (Could be based off of the `README.md` in `vscode-runme/examples` for simplicity)

**Comment by christian-bromann** [comment]
@sourishkrout I think we have this now:

![Screenshot 2023-08-11 at 15 06 02](https://github.com/stateful/docs.runme.dev/assets/731337/6cbc5223-8317-40f2-857c-52eb631a5a75)

It currently runs through a Node.js tutorial project which might be not ideal. We could discuss as a team what an ideal Hello World Runme notebook could look like.

**Comment by sourishkrout** [comment]
Redone installation instructions per client interface (Web, CLI, Extension, etc).
